import "dotenv/config";
import { PrismaClient } from "../generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({
  adapter,
});
const courses = [
  {
    name: "Mathematics Mastery",
    description: "Build strong mathematical foundations with interactive lessons.",
    subject: "Mathematics",
    grade: "Grade 5",
    price: 1499,
    teacherName: "Ananya Sharma",
    teacherRating: 4.8,
  },
  {
    name: "Science Explorer",
    description: "Explore science through experiments and real-world examples.",
    subject: "Science",
    grade: "Grade 5",
    price: 1299,
    teacherName: "Rahul Mehta",
    teacherRating: 4.7,
  },
  {
    name: "English Communication",
    description: "Improve grammar, vocabulary and communication skills.",
    subject: "English",
    grade: "Grade 6",
    price: 999,
    teacherName: "Priya Kapoor",
    teacherRating: 4.6,
  },
  {
    name: "Advanced Mathematics",
    description: "Strengthen problem-solving and advanced mathematical concepts.",
    subject: "Mathematics",
    grade: "Grade 7",
    price: 1899,
    teacherName: "Vikram Joshi",
    teacherRating: 4.9,
  },
  {
    name: "Physics Fundamentals",
    description: "Understand physics concepts with practical examples.",
    subject: "Physics",
    grade: "Grade 8",
    price: 1999,
    teacherName: "Arjun Rao",
    teacherRating: 4.8,
  },
  {
    name: "Creative Writing",
    description: "Develop creativity and storytelling skills.",
    subject: "English",
    grade: "Grade 7",
    price: 899,
    teacherName: "Neha Singh",
    teacherRating: 4.5,
  },
  {
    name: "Chemistry Basics",
    description: "Learn fundamental chemistry concepts through engaging lessons.",
    subject: "Chemistry",
    grade: "Grade 9",
    price: 1699,
    teacherName: "Sneha Patil",
    teacherRating: 4.7,
  },
  {
    name: "Biology for Beginners",
    description: "Discover cells, human biology and the natural world.",
    subject: "Biology",
    grade: "Grade 9",
    price: 1599,
    teacherName: "Karan Shah",
    teacherRating: 4.6,
  },
  {
    name: "Algebra Accelerator",
    description: "Master algebraic equations and problem-solving techniques.",
    subject: "Mathematics",
    grade: "Grade 8",
    price: 1799,
    teacherName: "Amit Verma",
    teacherRating: 4.9,
  },
  {
    name: "Coding for Kids",
    description: "Introduction to programming through fun and interactive projects.",
    subject: "Computer Science",
    grade: "Grade 6",
    price: 1499,
    teacherName: "Rohan Desai",
    teacherRating: 4.8,
  },
  {
    name: "Python Programming",
    description: "Learn Python programming from fundamentals to projects.",
    subject: "Computer Science",
    grade: "Grade 9",
    price: 2499,
    teacherName: "Aditya Kulkarni",
    teacherRating: 4.9,
  },
  {
    name: "Geometry Essentials",
    description: "Master shapes, angles, theorems and geometric reasoning.",
    subject: "Mathematics",
    grade: "Grade 6",
    price: 1199,
    teacherName: "Meera Iyer",
    teacherRating: 4.5,
  },
  {
    name: "World History",
    description: "Explore important civilizations and historical events.",
    subject: "History",
    grade: "Grade 8",
    price: 1099,
    teacherName: "Siddharth Jain",
    teacherRating: 4.4,
  },
  {
    name: "Geography Explorer",
    description: "Learn about maps, climate, resources and geography.",
    subject: "Geography",
    grade: "Grade 7",
    price: 999,
    teacherName: "Pooja Nair",
    teacherRating: 4.6,
  },
  {
    name: "Physics Problem Solving",
    description: "Solve challenging physics problems with expert guidance.",
    subject: "Physics",
    grade: "Grade 10",
    price: 2299,
    teacherName: "Raj Malhotra",
    teacherRating: 4.9,
  },
  {
    name: "Introduction to Robotics",
    description: "Learn robotics concepts and build beginner projects.",
    subject: "Computer Science",
    grade: "Grade 8",
    price: 2799,
    teacherName: "Nikhil Agarwal",
    teacherRating: 4.8,
  },
  {
    name: "Grammar Booster",
    description: "Improve English grammar with structured practice.",
    subject: "English",
    grade: "Grade 5",
    price: 799,
    teacherName: "Ritu Malhotra",
    teacherRating: 4.3,
  },
  {
    name: "Mental Math",
    description: "Improve calculation speed and mathematical confidence.",
    subject: "Mathematics",
    grade: "Grade 5",
    price: 699,
    teacherName: "Deepak Shah",
    teacherRating: 4.4,
  },
  {
    name: "Environmental Science",
    description: "Understand ecosystems, sustainability and environmental issues.",
    subject: "Science",
    grade: "Grade 7",
    price: 1199,
    teacherName: "Kavita Rao",
    teacherRating: 4.7,
  },
  {
    name: "Organic Chemistry",
    description: "Learn important organic chemistry concepts and reactions.",
    subject: "Chemistry",
    grade: "Grade 10",
    price: 2199,
    teacherName: "Dr. Manish Gupta",
    teacherRating: 4.9,
  },
  {
    name: "Human Biology",
    description: "Understand the human body and major biological systems.",
    subject: "Biology",
    grade: "Grade 10",
    price: 1999,
    teacherName: "Dr. Anjali Rao",
    teacherRating: 4.8,
  },
  {
    name: "French for Beginners",
    description: "Learn basic French vocabulary and conversational skills.",
    subject: "Languages",
    grade: "Grade 6",
    price: 1299,
    teacherName: "Claire Martin",
    teacherRating: 4.5,
  },
  {
    name: "Public Speaking",
    description: "Build confidence and become an effective speaker.",
    subject: "English",
    grade: "Grade 8",
    price: 1399,
    teacherName: "Shreya Kapoor",
    teacherRating: 4.7,
  },
  {
    name: "Statistics Fundamentals",
    description: "Learn data interpretation, probability and statistics.",
    subject: "Mathematics",
    grade: "Grade 10",
    price: 1899,
    teacherName: "Nitin Bansal",
    teacherRating: 4.6,
  },
  {
    name: "Web Development Basics",
    description: "Build your first websites using HTML, CSS and JavaScript.",
    subject: "Computer Science",
    grade: "Grade 10",
    price: 2299,
    teacherName: "Yash Thakur",
    teacherRating: 4.8,
  },
  {
    name: "Astronomy for Kids",
    description: "Discover planets, stars, galaxies and space exploration.",
    subject: "Science",
    grade: "Grade 6",
    price: 1099,
    teacherName: "Varun Menon",
    teacherRating: 4.7,
  },
  {
    name: "Indian History",
    description: "Explore major events and personalities from Indian history.",
    subject: "History",
    grade: "Grade 9",
    price: 1399,
    teacherName: "Ashish Sharma",
    teacherRating: 4.5,
  },
  {
    name: "Economics Fundamentals",
    description: "Understand basic economic concepts and real-world applications.",
    subject: "Economics",
    grade: "Grade 10",
    price: 1599,
    teacherName: "Sonal Mehta",
    teacherRating: 4.6,
  },
  {
    name: "Logical Reasoning",
    description: "Develop logical thinking and analytical problem-solving skills.",
    subject: "Mathematics",
    grade: "Grade 8",
    price: 999,
    teacherName: "Harsh Vora",
    teacherRating: 4.4,
  },
  {
    name: "AI for Young Minds",
    description: "Introduction to artificial intelligence through simple projects.",
    subject: "Computer Science",
    grade: "Grade 9",
    price: 2999,
    teacherName: "Tanvi Shah",
    teacherRating: 4.9,
  },
];

async function main() {
  await prisma.course.deleteMany();

  await prisma.course.createMany({
    data: courses,
  });

  console.log(`Seeded ${courses.length} courses`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });